name : deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: deploy via ssh
              uses: appleboy/ssh-action@v1.0.3
              with:
                 host: ${{ secrets.EC2_HOST }}
                 username: ${{ secrets.EC2_USER }}
                 key: ${{ secrets.EC2_SSH_KEY }}
                 script: |
                   export BUN_INSTALL="$HOME/.bun"
                   export PATH="$BUN_INSTALL/bin:$PATH"

                   cd /home/ubuntu/collabCode
                   git pull origin main
                   cd backend
                   bun install --production
                   # bun run build # (Commented out: No build script in root package.json)
                   pm2 reload app || pm2 start src/index.ts --name "app" --interpreter ~/.bun/bin/bun --interpreter-args "--env-file=.env"
                   pm2 save
                   
